version: "3"
services:
  backend:
    image: herasj23/pf-services:v1.0.2
    container_name: pf-services
    restart: always
    env_file:
      - ./.env
    build:
      context: ./pf-backend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
  model:
    # image: herasj23/pf-ml:v0.5
    container_name: pf-ml
    #restart: always
    env_file:
      - ./.env
    build:
      context: ./pf-ml
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
