version: "3"
services:
  backend:
    container_name: pf-services
    restart: always
    env_file:
      - ./.env
    build:
      context: ./pf-backend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
