authorName: KodeWil
experimentName: NLP
trialConcurrency: 1
maxExecDuration: 3h
maxTrialNum: 20
trainingServicePlatform: local
useAnnotation: false
searchSpacePath: search_space.json
tuner: 
  builtinTunerName: TPE
  classArgs: 
    optimize_mode: maximize

trial:
  command: python3 mainTrain.py
  codeDir: .
    
