name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get the version
      id: getTag
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Echo
      run: echo ${{ steps.getTag.outputs }}
